#! /usr/bin/env python3
# regex code generated by regex101.com

import re
import json
from netmiko import ConnectHandler
import sys

regex = re.compile(r"(?P<vlan>\d+)\s+(?P<mac>\w+.\w+.\w+)\s+(?P<type>\w+)\s+(?P<ports>Et+\d+)\s+(?P<moves>\d+)\s+(?P<last_move>\d+\:+\d\d\:\d\d\s+\w+)")
mymac = "0050.7966.6800"

def net_connect():
	connection = ConnectHandler(host="192.168.107.131", port="22", username="xxx", password="xxx", device_type="arista_eos")
	command_output = connection.send_command("show mac address-table")
	return command_output

# when using a dictionary  entries like ca01.09dc.001c are returned only once even if they occur multiple times.

def mac_list(regex, mymac):
	regex = regex
	lookfor = mymac
	macaddr_list = net_connect()
	mylist = []
	for line in macaddr_list.splitlines():
		line = line.strip()
		m = regex.match(line)
		if m:
			group = m.groupdict() # every line becomes a dict with multiple key, value pairs
			mylist.append(group) # nest each dict in a list
	for entry in mylist:
		if lookfor in entry['mac']:
			print("MAC " + lookfor +" is present on port " + entry['ports'])
# print full list below
	print("here is the full list: \n")
	print(json.dumps(mylist, indent=4, sort_keys=True) + '\n')


if __name__ == "__main__":
	#validate_mac(regex)
	mac_list(regex, mymac)
